[tool.ruff]
# Don't type on slightly wide punch cards anymore
line-length = 120

[tool.codespell]
# Ref: https://github.com/codespell-project/codespell#using-a-config-file
skip = '.git*'
check-hidden = true
# ignore-regex = ''
# ignore-words-list = ''
