# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
#
name: Publish chart

# Trigger the workflow on pushed tags or commits to main branch.
on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/publish-chart.yaml"
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/publish-chart.yaml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
    tags:
      - "**"

jobs:
  # Packages the Helm chart, and pushes it to cryptnono/cryptnono@gh-pages.
  #
  publish:
    runs-on: ubuntu-22.04

    # Explicitly request permissions to push to this git repository's gh-pages
    # branch via the the GITHUB_TOKEN we can have access to.
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          # chartpress requires the full history
          fetch-depth: 0
          # We vendor kubectl-trace as a submodule to build the fetch-kernel-headers image
          submodules: recursive

      - uses: actions/setup-python@v3

      - name: Set up QEMU (for docker buildx)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx (for chartpress)
        uses: docker/setup-buildx-action@v3

      - name: store whether we are publishing the chart
        id: publishing
        shell: python
        run: |
          publishing = ""
          if (
              "${{ github.repository }}" == "cryptnono/cryptnono"
              and "${{ github.event_name }}" == "push"
              and (
                  "${{ github.event.ref }}".startswith("refs/tags/")
                  or
                  "${{ github.event.ref }}" == "refs/heads/main"
              )
          ):
              publishing = "true"
              print("Publishing chart")
          print(f"::set-output name=publishing::{publishing}")

      - name: Setup push rights to Quay.io
        if: steps.publishing.outputs.publishing
        run: |
          docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: Install dependencies
        run: |
          pip install -r dev-requirements.txt
          pip list
          helm version

      - name: Configure a git user
        run: |
          git config --global user.email "github-actions@example.local"
          git config --global user.name "GitHub Actions user"

      - name: Build image, push if necessary
        env:
          PUBLISHING: ${{ steps.publishing.outputs.publishing }}
        run: |
          CHARTPRESS_ARGS=""
          if [[ "${PUBLISHING}" == "true" ]]; then
            CHARTPRESS_ARGS="--push"
          fi
          chartpress \
            --builder docker-buildx \
            --platform linux/amd64 --platform linux/arm64 \
            ${CHARTPRESS_ARGS}

      - name: Publish chart with chartpress
        if: steps.publishing.outputs.publishing
        env:
          GITHUB_TOKEN: "${{ github.token }}"
        run: |
          set -eux

          PUBLISH_ARGS="--publish-chart --push"

          if [[ $GITHUB_REF != refs/tags/* ]]; then
              PR_OR_HASH=$(git log -1 --pretty=%h-%B | head -n1 | sed 's/^.*\(#[0-9]*\).*/\1/' | sed 's/^\([0-9a-f]*\)-.*/@\1/')
              LATEST_COMMIT_TITLE=$(git log -1 --pretty=%B | head -n1)
              EXTRA_MESSAGE="${{ github.repository }}${PR_OR_HASH} ${LATEST_COMMIT_TITLE}"
              chartpress $PUBLISH_ARGS --extra-message "${EXTRA_MESSAGE}"
          else
              chartpress $PUBLISH_ARGS --tag "${GITHUB_REF:10}"
          fi

          git --no-pager diff --color
